on:
  push:
    tags:
      - "v*"
jobs:
  release:
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/configure-xcode
      - name: Build
        run: ./build.sh
      - name: Create and publish release
        run: |
          TAG="${{ github.ref_name }}"
          gh release create "$TAG" --draft --title "$TAG"
          gh release upload "$TAG" out/*.dylib
